## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Add value counts to a variable
value_counts = application_df['APPLICATION_TYPE'].value_counts()

# Create a list of application types to be replaced (500 is cutoff value)
application_types_to_replace = list(value_counts[value_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df.loc[application_df['APPLICATION_TYPE'] == app, 'APPLICATION_TYPE'] = 'Other'

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df["CLASSIFICATION"].value_counts()[application_df["CLASSIFICATION"].value_counts() > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Add value counts to a variable
value_counts = application_df["CLASSIFICATION"].value_counts()

# Create a list of application types to be replaced (500 is cutoff value)
classifications_to_replace = list(value_counts[value_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df.loc[application_df['CLASSIFICATION'] == cls, 'CLASSIFICATION'] = 'Other'

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(application_df, dtype=int)
dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = dummies["IS_SUCCESSFUL"].values
X = dummies.drop(columns = "IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [69]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  20
hidden_nodes_layer2 = 12
hidden_nodes_layer3 = 8

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_42 (Dense)                │ (None, 20)             │           880 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 12)             │           252 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,245 (4.86 KB)

 Trainable params: 1,245 (4.86 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [71]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 307us/step - accuracy: 0.6573 - loss: 0.6232
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7261 - loss: 0.5613
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7291 - loss: 0.5560
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7336 - loss: 0.5481
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7306 - loss: 0.5510
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7305 - loss: 0.5522
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7325 - loss: 0.5452
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 286us/step - accuracy: 0.7298 - loss: 0.5508
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.7312 - loss: 0.5486
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7263 - loss: 0.5551
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7303 - loss: 0.5506
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step - accuracy: 0.7341 - loss: 0.5479
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - accuracy: 0.7366 - loss: 0.5424
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.7341 - loss: 0.5446
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.7380 - loss: 0.5446
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7292 - loss: 0.5493
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7330 - loss: 0.5468
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7399 - loss: 0.5386
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.7368 - loss: 0.5409
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.7368 - loss: 0.5456
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - accuracy: 0.7357 - loss: 0.5430
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 332us/step - accuracy: 0.7359 - loss: 0.5439
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 287us/step - accuracy: 0.7342 - loss: 0.5449
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7347 - loss: 0.5436
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7308 - loss: 0.5502
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7353 - loss: 0.5414
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7385 - loss: 0.5409
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7309 - loss: 0.5443
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7346 - loss: 0.5439
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7372 - loss: 0.5392
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7330 - loss: 0.5437
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 338us/step - accuracy: 0.7385 - loss: 0.5414
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7342 - loss: 0.5425
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.7342 - loss: 0.5445
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7423 - loss: 0.5382
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7374 - loss: 0.5372
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7336 - loss: 0.5419
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7335 - loss: 0.5466
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7378 - loss: 0.5426
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7350 - loss: 0.5456
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7367 - loss: 0.5412
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7371 - loss: 0.5403
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7363 - loss: 0.5414
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7361 - loss: 0.5446
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7334 - loss: 0.5414
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7414 - loss: 0.5365
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.7344 - loss: 0.5439
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - accuracy: 0.7358 - loss: 0.5403
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7415 - loss: 0.5339
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7401 - loss: 0.5352
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - accuracy: 0.7354 - loss: 0.5429
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7412 - loss: 0.5370
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.7429 - loss: 0.5352
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7374 - loss: 0.5417
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - accuracy: 0.7398 - loss: 0.5376
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7414 - loss: 0.5344
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7365 - loss: 0.5404
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7413 - loss: 0.5369
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - accuracy: 0.7390 - loss: 0.5377
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 287us/step - accuracy: 0.7397 - loss: 0.5381
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.7352 - loss: 0.5439
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - accuracy: 0.7375 - loss: 0.5401
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - accuracy: 0.7409 - loss: 0.5373
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.7408 - loss: 0.5352
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.7379 - loss: 0.5406
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 296us/step - accuracy: 0.7344 - loss: 0.5416
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 294us/step - accuracy: 0.7372 - loss: 0.5396
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - accuracy: 0.7417 - loss: 0.5359
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - accuracy: 0.7343 - loss: 0.5410
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7364 - loss: 0.5410
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.7418 - loss: 0.5363
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7374 - loss: 0.5389
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7393 - loss: 0.5382
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7383 - loss: 0.5380
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - accuracy: 0.7359 - loss: 0.5451
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7366 - loss: 0.5408
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7359 - loss: 0.5409
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7388 - loss: 0.5389
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7359 - loss: 0.5403
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7374 - loss: 0.5367
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.7423 - loss: 0.5329
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7373 - loss: 0.5393
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 286us/step - accuracy: 0.7413 - loss: 0.5336
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7384 - loss: 0.5387
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7413 - loss: 0.5358
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7359 - loss: 0.5407
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7400 - loss: 0.5385
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - accuracy: 0.7413 - loss: 0.5360
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7385 - loss: 0.5374
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7376 - loss: 0.5390
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7382 - loss: 0.5342
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.7407 - loss: 0.5361
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7435 - loss: 0.5306
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7430 - loss: 0.5346
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7350 - loss: 0.5368
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7356 - loss: 0.5388
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - accuracy: 0.7374 - loss: 0.5372
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - accuracy: 0.7382 - loss: 0.5346
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 296us/step - accuracy: 0.7412 - loss: 0.5313
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - accuracy: 0.7368 - loss: 0.5383

In [72]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 385us/step - accuracy: 0.7269 - loss: 0.5551
Loss: 0.5550785660743713, Accuracy: 0.7268804907798767

In [73]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimisation.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.